const wordData = [
  { word: "健身", meaning: "to work out", example: "我每天健身一小時。(I work out for an hour every day.)" },
  { word: "頭痛", meaning: "headache; to have a headache", example: "我今天有點頭痛。(I have a bit of a headache today.)" },
  { word: "拉肚子", meaning: "to have diarrhea", example: "他昨天吃壞肚子，拉肚子了一整天。(He got sick from food and had diarrhea all day.)" },
  { word: "看病", meaning: "to see a doctor", example: "她明天要去醫院看病。(She will go to the hospital to see a doctor tomorrow.)" },
  { word: "老是", meaning: "always (negatively)", example: "你老是遲到。(You are always late.)" },
  { word: "改", meaning: "to change; to correct", example: "你應該改一下你的壞習慣。(You should change your bad habits.)" },
  { word: "健身房", meaning: "gym", example: "我常在健身房運動。(I often work out at the gym.)" },
  { word: "從小", meaning: "since childhood", example: "我從小就喜歡跑步。(I’ve liked running since I was young.)" },
  { word: "操場", meaning: "playground; sports field", example: "他在操場跑步。(He is running on the field.)" },
  { word: "體育", meaning: "physical education; sports", example: "我最喜歡的課是體育課。(My favorite class is PE.)" },
  { word: "腿", meaning: "leg", example: "跑太多會腿酸。(Running too much makes your legs sore.)" },
  { word: "脖子", meaning: "neck", example: "我的脖子有點痛。(My neck feels a little sore.)" },
  { word: "死", meaning: "to die (also used for emphasis)", example: "熱死了！(It’s extremely hot!)" },
  { word: "誇張", meaning: "exaggerated", example: "你太誇張了吧。(You’re exaggerating too much.)" },
  { word: "叫", meaning: "to call; to shout", example: "快叫醫生！(Call the doctor quickly!)" },
  { word: "救護車", meaning: "ambulance", example: "他受傷了，需要救護車。(He is injured and needs an ambulance.)" },
  { word: "送", meaning: "to send; to deliver; to take (someone)", example: "我送你去醫院。(I’ll take you to the hospital.)" },
  { word: "救命", meaning: "help!; to save a life", example: "救命啊！有人跌倒了！(Help! Someone fell!)" },
  { word: "照", meaning: "to take (a photo/X-ray)", example: "醫生要我去照X光。(The doctor asked me to take an X-ray.)" },
  { word: "教練", meaning: "coach; trainer", example: "我的健身教練很專業。(My gym coach is very professional.)" },
  { word: "變", meaning: "to change; become", example: "他最近變瘦了。(He became thinner recently.)" },
  { word: "體重", meaning: "weight", example: "我的體重增加了。(My weight increased.)" },
  { word: "減", meaning: "to reduce; to lose (weight)", example: "我想減五公斤。(I want to lose five kilograms.)" },
  { word: "下", meaning: "to drop; to fall", example: "他的體重下了三公斤。(His weight dropped by three kilograms.)" },
  { word: "年紀", meaning: "age", example: "他年紀大了，需要多休息。(He is older and needs more rest.)" },
  { word: "男人", meaning: "man", example: "他是一個很努力的男人。(He is a hardworking man.)" },
  { word: "女人", meaning: "woman", example: "那位女人是老師。(That woman is a teacher.)" },
  { word: "老人", meaning: "elderly person", example: "這裡有很多老人運動。(Many elderly people exercise here.)" },
  { word: "青菜", meaning: "vegetable (leafy)", example: "多吃青菜對身體好。(Eating vegetables is good for your health.)" },
  { word: "漢堡", meaning: "hamburger", example: "我想吃一個漢堡。(I want to eat a hamburger.)" },
  { word: "薯條", meaning: "french fries", example: "我不敢吃太多薯條。(I try not to eat too many fries.)" },
  { word: "餅乾", meaning: "cookies; crackers", example: "他喜歡吃甜的餅乾。(She likes sweet cookies.)" },
  { word: "飲食", meaning: "diet; eating habits", example: "要注意飲食才會健康。(You need to watch your diet to stay healthy.)" },
  { word: "油", meaning: "oil", example: "這道菜太油了。(This dish is too oily.)" },
  { word: "鹽", meaning: "salt", example: "你加太多鹽了。(You added too much salt.)" },
  { word: "可樂", meaning: "cola", example: "他常喝可樂。(He often drinks cola.)" },
  { word: "開水", meaning: "boiled water; plain water", example: "我只喝開水。(I only drink plain water.)" },
  { word: "來不及", meaning: "too late to; not enough time", example: "我來不及吃早餐。(I didn’t have time for breakfast.)" },
  { word: "來得及", meaning: "still have time to", example: "還來得及改變。(It’s still not too late to change.)" },
  { word: "三餐", meaning: "three meals", example: "三餐要吃得均衡。(Eat balanced meals.)" },
  { word: "餐", meaning: "meal", example: "這餐很好吃。(This meal is delicious.)" },
  { word: "國王", meaning: "king", example: "他覺得自己吃飯像國王。(He feels like a king when he eats.)" },
  { word: "到底", meaning: "exactly; on earth", example: "你到底想說什麼？(What exactly do you want to say?)" },
  { word: "活", meaning: "to live", example: "他活得很健康。(He lives a healthy life.)" },
  { word: "訓練", meaning: "training; to train", example: "這是很好的肌力訓練。(This is a good strength training exercise.)" },
  { word: "慢跑", meaning: "jogging; to jog", example: "我每天慢跑二十分鐘。(I jog for 20 minutes every day.)" }
];
