const wordData = [
  { word: "健身", meaning: "to work out", example: "我每天健身一小时。(I work out for an hour every day.)" },
  { word: "头痛", meaning: "headache; to have a headache", example: "我今天有点头痛。(I have a bit of a headache today.)" },
  { word: "拉肚子", meaning: "to have diarrhea", example: "他昨天吃坏肚子，拉肚子了一整天。(He got sick from food and had diarrhea all day.)" },
  { word: "看病", meaning: "to see a doctor", example: "她明天要去医院看病。(She will go to the hospital to see a doctor tomorrow.)" },
  { word: "老是", meaning: "always (negatively)", example: "你老是迟到。(You are always late.)" },
  { word: "改", meaning: "to change; to correct", example: "你应该改一下你的坏习惯。(You should change your bad habits.)" },
  { word: "健身房", meaning: "gym", example: "我常在健身房运动。(I often work out at the gym.)" },
  { word: "从小", meaning: "since childhood", example: "我从小就喜欢跑步。(I’ve liked running since I was young.)" },
  { word: "操场", meaning: "playground; sports field", example: "他在操场跑步。(He is running on the field.)" },
  { word: "体育", meaning: "physical education; sports", example: "我最喜欢的课是体育课。(My favorite class is PE.)" },
  { word: "腿", meaning: "leg", example: "跑太多会腿酸。(Running too much makes your legs sore.)" },
  { word: "脖子", meaning: "neck", example: "我的脖子有点痛。(My neck feels a little sore.)" },
  { word: "死", meaning: "to die (also used for emphasis)", example: "热死了！(It’s extremely hot!)" },
  { word: "夸张", meaning: "exaggerated", example: "你太夸张了吧。(You’re exaggerating too much.)" },
  { word: "叫", meaning: "to call; to shout", example: "快叫医生！(Call the doctor quickly!)" },
  { word: "救护车", meaning: "ambulance", example: "他受伤了，需要救护车。(He is injured and needs an ambulance.)" },
  { word: "送", meaning: "to send; to deliver; to take (someone)", example: "我送你去医院。(I’ll take you to the hospital.)" },
  { word: "救命", meaning: "help!; to save a life", example: "救命啊！有人跌倒了！(Help! Someone fell!)" },
  { word: "照", meaning: "to take (a photo/X-ray)", example: "医生要我去照X光。(The doctor asked me to take an X-ray.)" },
  { word: "教练", meaning: "coach; trainer", example: "我的健身教练很专业。(My gym coach is very professional.)" },
  { word: "变", meaning: "to change; become", example: "他最近变瘦了。(He became thinner recently.)" },
  { word: "体重", meaning: "weight", example: "我的体重增加了。(My weight increased.)" },
  { word: "减", meaning: "to reduce; to lose (weight)", example: "我想减五公斤。(I want to lose five kilograms.)" },
  { word: "下", meaning: "to drop; to fall", example: "他的体重下了三公斤。(His weight dropped by three kilograms.)" },
  { word: "年纪", meaning: "age", example: "他年纪大了，需要多休息。(He is older and needs more rest.)" },
  { word: "男人", meaning: "man", example: "他是一个很努力的男人。(He is a hardworking man.)" },
  { word: "女人", meaning: "woman", example: "那位女人是老师。(That woman is a teacher.)" },
  { word: "老人", meaning: "elderly person", example: "这里有很多老人运动。(Many elderly people exercise here.)" },
  { word: "青菜", meaning: "vegetable (leafy)", example: "多吃青菜对身体好。(Eating vegetables is good for your health.)" },
  { word: "汉堡", meaning: "hamburger", example: "我想吃一个汉堡。(I want to eat a hamburger.)" },
  { word: "薯条", meaning: "french fries", example: "我不敢吃太多薯条。(I try not to eat too many fries.)" },
  { word: "饼干", meaning: "cookies; crackers", example: "他喜欢吃甜的饼干。(She likes sweet cookies.)" },
  { word: "饮食", meaning: "diet; eating habits", example: "要注意饮食才会健康。(You need to watch your diet to stay healthy.)" },
  { word: "油", meaning: "oil", example: "这道菜太油了。(This dish is too oily.)" },
  { word: "盐", meaning: "salt", example: "你加太多盐了。(You added too much salt.)" },
  { word: "可乐", meaning: "cola", example: "他常喝可乐。(He often drinks cola.)" },
  { word: "开水", meaning: "boiled water; plain water", example: "我只喝开水。(I only drink plain water.)" },
  { word: "来不及", meaning: "too late to; not enough time", example: "我来不及吃早餐。(I didn’t have time for breakfast.)" },
  { word: "来得及", meaning: "still have time to", example: "还来得及改变。(It’s still not too late to change.)" },
  { word: "三餐", meaning: "three meals", example: "三餐要吃得均衡。(Eat balanced meals.)" },
  { word: "餐", meaning: "meal", example: "这餐很好吃。(This meal is delicious.)" },
  { word: "国王", meaning: "king", example: "他觉得自己吃饭像国王。(He feels like a king when he eats.)" },
  { word: "到底", meaning: "exactly; on earth", example: "你到底想说什么？(What exactly do you want to say?)" },
  { word: "活", meaning: "to live", example: "他活得很健康。(He lives a healthy life.)" },
  { word: "训练", meaning: "training; to train", example: "这是很好的肌力训练。(This is a good strength training exercise.)" },
  { word: "慢跑", meaning: "jogging; to jog", example: "我每天慢跑二十分钟。(I jog for 20 minutes every day.)" }
];
